# Generated by Django 6.0.6 on 2026-06-09 16:13

import django.db.models.deletion
from django.conf import settings
from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),
    ]

    operations = [
        migrations.CreateModel(
            name='userProfile',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('age', models.IntegerField(null=True)),
                ('income', models.IntegerField(null=True)),
                ('cast', models.CharField(max_length=100)),
                ('state', models.CharField(max_length=100)),
                ('profession', models.CharField(max_length=100)),
                ('education_level', models.CharField(blank=True, choices=[('primary', 'Primary School'), ('secondary', 'Secondary School'), ('higher_secondary', 'Higher Secondary (12th)'), ('undergraduate', 'Undergraduate (Bachelor Degree)'), ('postgraduate', 'Postgraduate (Master/PhD)'), ('none', 'None')], default='none', max_length=50, null=True)),
                ('life_stage', models.CharField(blank=True, choices=[('newborn_parent', 'Parent of Newborn'), ('student', 'Student'), ('young_adult', 'Young Adult'), ('mid_age', 'Mid-Age Citizen'), ('senior_citizen', 'Senior Citizen')], default='young_adult', max_length=50, null=True)),
                ('preferred_language', models.CharField(choices=[('en', 'English'), ('hi', 'Hindi'), ('mr', 'Marathi'), ('gu', 'Gujarati'), ('ta', 'Tamil'), ('te', 'Telugu'), ('bn', 'Bengali'), ('kn', 'Kannada')], default='en', max_length=10, null=True)),
                ('date_created', models.DateTimeField(auto_now_add=True, null=True)),
                ('user', models.OneToOneField(on_delete=django.db.models.deletion.CASCADE, to=settings.AUTH_USER_MODEL)),
            ],
        ),
    ]
