# Generated by Django 6.0.6 on 2026-06-09 16:13

import datetime
import django.db.models.deletion
from django.conf import settings
from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
        ('documents', '0001_initial'),
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),
    ]

    operations = [
        migrations.CreateModel(
            name='Schemes',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('title_en', models.CharField(max_length=100)),
                ('title_hi', models.CharField(blank=True, max_length=100, null=True)),
                ('title_mr', models.CharField(blank=True, max_length=100, null=True)),
                ('description_en', models.TextField()),
                ('description_hi', models.TextField(blank=True, null=True)),
                ('description_mr', models.TextField(blank=True, null=True)),
                ('scheme_application_start_date', models.DateField(blank=True, null=True)),
                ('deadline_scheme_application', models.DateField(blank=True, null=True)),
                ('age_limit', models.IntegerField()),
                ('income_limit', models.IntegerField()),
                ('caste', models.CharField(max_length=100)),
                ('state', models.CharField(max_length=100)),
                ('profession', models.CharField(max_length=100)),
                ('category', models.CharField(blank=True, max_length=100, null=True)),
                ('deadline', models.DateField(blank=True, null=True)),
                ('date_created', models.DateTimeField(default=datetime.datetime.now)),
                ('scheme_type', models.CharField(choices=[('government', 'Government'), ('private', 'Private')], default='government', max_length=20)),
                ('required_documents', models.ManyToManyField(to='documents.documents')),
            ],
        ),
        migrations.CreateModel(
            name='Notification',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('message', models.TextField()),
                ('is_read', models.BooleanField(default=False)),
                ('created_at', models.DateTimeField(auto_now_add=True)),
                ('type', models.CharField(choices=[('new', 'New Scheme'), ('deadline', 'Deadline')], max_length=50)),
                ('user', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to=settings.AUTH_USER_MODEL)),
                ('scheme', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='schemes.schemes')),
            ],
        ),
        migrations.AddIndex(
            model_name='schemes',
            index=models.Index(fields=['state', 'age_limit', 'income_limit', 'scheme_type'], name='schemes_sch_state_0fbe8d_idx'),
        ),
    ]
