# Generated by Django 6.0.6 on 2026-06-09 16:13

from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
    ]

    operations = [
        migrations.CreateModel(
            name='Documents',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('state', models.CharField(blank=True, max_length=100, null=True)),
                ('caste', models.CharField(blank=True, max_length=100, null=True)),
                ('min_age', models.PositiveIntegerField(blank=True, null=True)),
                ('max_age', models.PositiveIntegerField(blank=True, null=True)),
                ('profession', models.CharField(blank=True, max_length=100, null=True)),
                ('title_en', models.CharField(max_length=200)),
                ('title_hi', models.CharField(blank=True, max_length=200, null=True)),
                ('title_mr', models.CharField(blank=True, max_length=200, null=True)),
                ('description_en', models.TextField()),
                ('description_hi', models.TextField(blank=True, null=True)),
                ('description_mr', models.TextField(blank=True, null=True)),
                ('category', models.CharField(max_length=150)),
                ('preferred_age', models.PositiveIntegerField(blank=True, null=True)),
                ('image', models.ImageField(blank=True, null=True, upload_to='documents/images/')),
                ('required_for_application', models.BooleanField(default=False)),
                ('how_to_get_document_en', models.TextField(blank=True, null=True)),
                ('how_to_get_document_hi', models.TextField(blank=True, null=True)),
                ('how_to_get_document_mr', models.TextField(blank=True, null=True)),
                ('issuing_authority', models.CharField(blank=True, max_length=200, null=True)),
                ('date_created', models.DateTimeField(auto_now_add=True)),
            ],
        ),
        migrations.CreateModel(
            name='ServiceCenter',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('name', models.CharField(max_length=200)),
                ('center_type', models.CharField(choices=[('csc', 'Common Service Center (CSC)'), ('rto', 'RTO Office'), ('municipal', 'Municipal Corporation Office'), ('post_office', 'Post Office'), ('cyber_cafe', 'Cyber Café (Authorized)'), ('other', 'Other Government Office')], default='csc', max_length=50)),
                ('address', models.TextField()),
                ('city', models.CharField(max_length=100)),
                ('state', models.CharField(max_length=100)),
                ('pin_code', models.CharField(max_length=10)),
                ('contact_number', models.CharField(blank=True, max_length=20, null=True)),
                ('timings', models.CharField(default='9:00 AM - 6:00 PM', max_length=100)),
                ('services_offered', models.TextField(help_text='Comma separated list of services (e.g., Aadhaar Card, PAN Card)')),
                ('latitude', models.DecimalField(blank=True, decimal_places=6, max_digits=9, null=True)),
                ('longitude', models.DecimalField(blank=True, decimal_places=6, max_digits=9, null=True)),
                ('date_created', models.DateTimeField(auto_now_add=True)),
            ],
        ),
    ]
